apiVersion: v1
kind: Service
metadata:
  name: iotex-veracruz-app
spec:
  selector:
    iotex-veracruz: app
  ports:
    - protocol: TCP
      port: 5000
      name: iotex-veracruz-app
  externalIPs:
    - 172.31.4.186
